### ISSUE TITLE
Potential memory leak reported by static analyzer

### ISSUE THREAD

**Issue by danix800** [darlinghq/darling-bootstrap_cmds#6]
https://github.com/darlinghq/darling-bootstrap_cmds/blob/0f300a7a04bb1174a3b7db58b57d738aadc14e13/migcom.tproj/header.c#L474

`protect` is never released.

**Comment by danix800** [comment]
https://github.com/darlinghq/darling-bootstrap_cmds/blob/0f300a7a04bb1174a3b7db58b57d738aadc14e13/migcom.tproj/header.c#L356

`up` too.

**Comment by LubosD** [comment]
This is a clone of original Apple source code. We don't fix these bugs, such fixes would be easily overwritten during next source code import.

Report them to Apple directly if you want them fixed.
